---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels: 
    app: sql
spec:
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql-container
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: secretsql
              key: database

