version: "3.7"

services:
  flask-app:
    build: ./
    image: sherazshahid017/myflask-app:latest
    ports:
    - target: 5000
      published: 5000
      protocol: tcp


  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf
